name: demo_custom_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  analyzer: ^5.4.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.1.0
